[build-system]
requires = ["maturin>=1.15.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
features = ["extension-module"]

[project]
name = "clvk_tools_rs"
dynamic = ["version"]

# - Reenable these when we switch over from clvk_tools.
# [project.scripts]
# brun = "clvk_tools_rs.cmds:brun"
# run = "clvk_tools_rs.cmds:run"
# opc = "clvk_tools_rs.cmds:opc"
# opd = "clvk_tools_rs.cmds:opd"
# cldb = "clvk_tools_rs.cmds:cldb"
